export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const PROVIDE_RESET_EMAIL = 'PROVIDE_RESET_EMAIL';
export const RESET_PASSWORD = 'SEND_RESET_EMAIL';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
