import reducers from '../src/reducers';
import getCategories from '../src/reducers/GetCategories';
import data from './landing_page/maxios_mock';


describe('Test all reducers', () => {
  it('Given article reducer should handle ARTICLES', () => {
    expect(
      getCategories([], {
        type: 'CATEGORIES',
        categories: data.category.categorys.results,
      }),
    ).toEqual(
      data.category.categorys.results,
    );
  });


  it('reducers', () => {
    let state;
    state = reducers({ categories: [{ name: 'Entertainment', slug: 'entertainment' }, { name: 'politics', slug: 'politics' }, { name: 'sport', slug: 'sport' }, { name: 'music', slug: 'music' }, { name: 'bongos', slug: 'bongos' }, { name: 'bongos', slug: 'bongos-1' }], articles: [], registrationReducer: { error: null, successMsg: null, loading: false } }, {
      type: 'ARTICLES',
      articles: [{
        slug: 'kati-the-cat',
        title: 'Kati! the cat',
        description: 'Cat that Chryce claims he had',
        body: 'Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T14:17:34.576544+03:00',
        updated_at: '2019-04-12T14:17:54.150320+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T12:11:51.929628+03:00', favorite_articles: [], user: 'Timothy Edgar Nyabongo',
        },
        tagList: ['pet', 'love', 'lies'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }, {
        slug: 'ipso-lorum-2',
        title: 'Ipso Lorum',
        description: 'writer',
        body: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). Where does it come from? Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \'de Finibus Bonorum et Malorum\' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham. Where can I get some? There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T11:23:12.266689+03:00',
        updated_at: '2019-04-12T11:23:26.657446+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['writing', 'poem'],
        likes: 0,
        dislikes: 0,
        reading_time: '9 min read',
        read_stats: 0,
      }, {
        slug: 'ipso-lorum-1',
        title: 'Ipso Lorum',
        description: 'writer',
        body: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). Where does it come from? Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \'de Finibus Bonorum et Malorum\' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham. Where can I get some? There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T11:21:37.167822+03:00',
        updated_at: '2019-04-12T11:21:54.778659+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['writing', 'poem'],
        likes: 0,
        dislikes: 0,
        reading_time: '4 min read',
        read_stats: 0,
      }, {
        slug: 'kenya-get-beaten-70',
        title: 'Kenya get beaten 7:0',
        description: 'Afcon Qualifiers',
        body: 'Tanzania had a great day when they met Kenya in the East African Derby where Uganda was thrushed by 3 goals to 0.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T10:01:24.339277+03:00',
        updated_at: '2019-04-12T10:01:39.144685+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['football', 'soccer'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }, {
        slug: 'uganda-get-beaten-50',
        title: 'Uganda get beaten 5:0',
        description: 'Afcon Qualifiers',
        body: 'Tanzania had a great day when they met Uganda in the East African Derby where Uganda was thrushed by 3 goals to 0.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T10:00:34.722082+03:00',
        updated_at: '2019-04-12T10:00:48.830572+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['football', 'soccer'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }],
    });
    expect(state).toEqual({
      categories: [{ name: 'Entertainment', slug: 'entertainment' }, { name: 'politics', slug: 'politics' }, { name: 'sport', slug: 'sport' }, { name: 'music', slug: 'music' }, { name: 'bongos', slug: 'bongos' }, { name: 'bongos', slug: 'bongos-1' }],
      articles: [{
        slug: 'kati-the-cat',
        title: 'Kati! the cat',
        description: 'Cat that Chryce claims he had',
        body: 'Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T14:17:34.576544+03:00',
        updated_at: '2019-04-12T14:17:54.150320+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T12:11:51.929628+03:00', favorite_articles: [], user: 'Timothy Edgar Nyabongo',
        },
        tagList: ['pet', 'love', 'lies'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }, {
        slug: 'ipso-lorum-2',
        title: 'Ipso Lorum',
        description: 'writer',
        body: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). Where does it come from? Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \'de Finibus Bonorum et Malorum\' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham. Where can I get some? There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T11:23:12.266689+03:00',
        updated_at: '2019-04-12T11:23:26.657446+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['writing', 'poem'],
        likes: 0,
        dislikes: 0,
        reading_time: '9 min read',
        read_stats: 0,
      }, {
        slug: 'ipso-lorum-1',
        title: 'Ipso Lorum',
        description: 'writer',
        body: 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Why do we use it? It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). Where does it come from? Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \'de Finibus Bonorum et Malorum\' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham. Where can I get some? There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T11:21:37.167822+03:00',
        updated_at: '2019-04-12T11:21:54.778659+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['writing', 'poem'],
        likes: 0,
        dislikes: 0,
        reading_time: '4 min read',
        read_stats: 0,
      }, {
        slug: 'kenya-get-beaten-70',
        title: 'Kenya get beaten 7:0',
        description: 'Afcon Qualifiers',
        body: 'Tanzania had a great day when they met Kenya in the East African Derby where Uganda was thrushed by 3 goals to 0.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T10:01:24.339277+03:00',
        updated_at: '2019-04-12T10:01:39.144685+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['football', 'soccer'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }, {
        slug: 'uganda-get-beaten-50',
        title: 'Uganda get beaten 5:0',
        description: 'Afcon Qualifiers',
        body: 'Tanzania had a great day when they met Uganda in the East African Derby where Uganda was thrushed by 3 goals to 0.',
        category: { name: 'Entertainment', slug: 'entertainment' },
        average_rating: 0,
        user_rates: '0',
        created_at: '2019-04-12T10:00:34.722082+03:00',
        updated_at: '2019-04-12T10:00:48.830572+03:00',
        favorited: false,
        favorites_count: 0,
        is_published: true,
        author: {
          full_name: '', bio: '', image: null, follower_count: 0, following_count: 0, timestamp: '2019-04-12T09:47:35.542118+03:00', favorite_articles: [], user: 'nyabongo',
        },
        tagList: ['football', 'soccer'],
        likes: 0,
        dislikes: 0,
        reading_time: '1 min read',
        read_stats: 0,
      }],
      registrationReducer: { error: null, successMsg: null, loading: false },
      "login": {
        "errors": null,
        "isSuccessful": false,
        "token": "",
      }
    });
  });
});
