import reducers from '../src/reducers';
import getCategories from '../src/reducers/GetCategories';
import data from './landing_page/maxios_mock';

describe('Test all reducers', () => {
  it('Given article reducer should handle ARTICLES', () => {
    expect(
      getCategories([], {
        type: 'CATEGORIES',
        categories: data.category.categorys.results,
      })
    ).toEqual(data.category.categorys.results);
  });


  test('reducers', () => {
    let state;
    state = reducers({categories:[],articles:[],registrationReducer:{error:null,successMsg:null,loading:false},login:{isSuccessful:false,token:'',errors:null},socialauthReducer:{isAuthenticated:false,facebook_login:false,google_login:false,payload:'',token:''},allCategories:[],tags:[],newArticle:{title:'',description:'',body:'',category:'',tags:[]},userArticles:[],editArticle:{},allArticles:[]}, {type:'ALL_ARTICLES',articles:[{slug:'i-hate-stanley',title:'I hate Stanley',description:'I hate Stanley so so much',body:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',category:{name:'Peeps',slug:'peeps'},average_rating:0,user_rates:'0',created_at:'2019-04-16T13:46:13.350709+03:00',updated_at:'2019-04-16T13:46:36.127419+03:00',favorited:false,favorites_count:0,is_published:true,author:{full_name:'',bio:'',image:null,follower_count:0,following_count:0,timestamp:'2019-04-16T09:46:54.283425+03:00',favorite_articles:[],user:'LydiaNS'},tagList:['hate'],likes:0,dislikes:0,reading_time:'1 min read',read_stats:0},{slug:'hey-there',title:'Hey there',description:'My very first article',body:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',category:{name:'Peeps',slug:'peeps'},average_rating:0,user_rates:'0',created_at:'2019-04-16T09:53:36.176145+03:00',updated_at:'2019-04-16T13:44:16.148375+03:00',favorited:false,favorites_count:0,is_published:true,author:{full_name:'',bio:'',image:null,follower_count:0,following_count:0,timestamp:'2019-04-16T09:46:54.283425+03:00',favorite_articles:[],user:'LydiaNS'},tagList:['love'],likes:0,dislikes:0,reading_time:'1 min read',read_stats:0}]});
    expect(state).toEqual({categories:[],articles:[],registrationReducer:{error:null,successMsg:null,loading:false},login:{isSuccessful:false,token:'',errors:null},socialauthReducer:{isAuthenticated:false,facebook_login:false,google_login:false,payload:'',token:''},allCategories:[],tags:[],newArticle:{title:'',description:'',body:'',category:'',tags:[]},userArticles:[],editArticle:{},allArticles:[{slug:'i-hate-stanley',title:'I hate Stanley',description:'I hate Stanley so so much',body:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',category:{name:'Peeps',slug:'peeps'},average_rating:0,user_rates:'0',created_at:'2019-04-16T13:46:13.350709+03:00',updated_at:'2019-04-16T13:46:36.127419+03:00',favorited:false,favorites_count:0,is_published:true,author:{full_name:'',bio:'',image:null,follower_count:0,following_count:0,timestamp:'2019-04-16T09:46:54.283425+03:00',favorite_articles:[],user:'LydiaNS'},tagList:['hate'],likes:0,dislikes:0,reading_time:'1 min read',read_stats:0},{slug:'hey-there',title:'Hey there',description:'My very first article',body:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',category:{name:'Peeps',slug:'peeps'},average_rating:0,user_rates:'0',created_at:'2019-04-16T09:53:36.176145+03:00',updated_at:'2019-04-16T13:44:16.148375+03:00',favorited:false,favorites_count:0,is_published:true,author:{full_name:'',bio:'',image:null,follower_count:0,following_count:0,timestamp:'2019-04-16T09:46:54.283425+03:00',favorite_articles:[],user:'LydiaNS'},tagList:['love'],likes:0,dislikes:0,reading_time:'1 min read',read_stats:0}]});
  });
});

