const data = {
  article: {
    articles: {
      count: 8,
      next:
        'https://ah-backend-groot.herokuapp.com/api/articles/?limit=6&offset=6',
      previous: null,
      results: [
        {
          slug: 'wali-is-a-bold-guy',
          title: 'wali is a bold guy',
          description: 'He talks about his guy a lot',
          body:
            'Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T18:09:27.469655+03:00',
          updated_at: '2019-04-08T18:09:55.685559+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['rnb', 'soul', 'there'],
          likes: 0,
          dislikes: 0,
          reading_time: '1 min read',
          read_stats: 0,
        },
        {
          slug: 'nsanyu-trump',
          title: 'Nsanyu trump',
          description: 'An article about a guy who wants to be like trup',
          body:
            'Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other langua.',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T15:36:08.617171+03:00',
          updated_at: '2019-04-08T15:37:01.266345+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['rnb', 'soul', 'there'],
          likes: 0,
          dislikes: 0,
          reading_time: '2 min read',
          read_stats: 0,
        },
        {
          slug: 'mukasa-trump',
          title: 'Mukasa trump',
          description: 'An article about a guy who wants to be like trup',
          body:
            'Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.Take note that this article most likely applies to whatever other programming language you might be using, as these are concepts that exist in many other languages.',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T15:07:22.012008+03:00',
          updated_at: '2019-04-08T15:08:25.270165+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['rnb', 'soul', 'there'],
          likes: 0,
          dislikes: 0,
          reading_time: '3 min read',
          read_stats: 0,
        },
        {
          slug: 'me-is-you',
          title: 'me is you',
          description: 'am exceeding expectations in my LMS',
          body: 'Am be mama you',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T13:31:51.807640+03:00',
          updated_at: '2019-04-08T13:33:40.484441+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['hiphop', 'rnb', 'soul'],
          likes: 0,
          dislikes: 0,
          reading_time: '1 min read',
          read_stats: 0,
        },
        {
          slug: '8-th-aprils-is-such-a-beautiful-day-3',
          title: '8 th aprils is such a beautiful day',
          description: 'am exceeding expectations in my LMS',
          body: 'Am be mama you',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T13:31:30.885045+03:00',
          updated_at: '2019-04-08T13:33:21.788841+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['hiphop', 'rnb', 'soul'],
          likes: 0,
          dislikes: 0,
          reading_time: '1 min read',
          read_stats: 0,
        },
        {
          slug: '8-th-aprils-is-such-a-beautiful-day-2',
          title: '8 th aprils is such a beautiful day',
          description: 'am exceeding expectations in my LMS',
          body: 'Am be mama you',
          category: {
            name: 'Health',
            slug: 'health',
          },
          average_rating: 0,
          user_rates: '0',
          created_at: '2019-04-08T13:31:29.890472+03:00',
          updated_at: '2019-04-08T13:32:14.646742+03:00',
          favorited: false,
          favorites_count: 0,
          is_published: true,
          author: {
            full_name: '',
            bio: '',
            image: null,
            follower_count: 0,
            following_count: 0,
            timestamp: '2019-04-08T13:29:00.463973+03:00',
            favorite_articles: [],
            user: 'stanley',
          },
          tagList: ['hiphop', 'rnb', 'soul'],
          likes: 0,
          dislikes: 0,
          reading_time: '1 min read',
          read_stats: 0,
        },
      ],
    },
  },
  category: {
    categorys: {
      count: 5,
      next: null,
      previous: null,
      results: [
        {
          name: 'Head lines',
          slug: 'head-lines',
        },
        {
          name: 'Music',
          slug: 'music',
        },
      ],
    },
  },
};

export default data;
